version: "2.2"

services:

  web:
    build: .
    volumes:
      - ./web:/var/www/web
    working_dir: /var/www/web
    user: "www-data"
    ports:
      - 9000:9000

  nginx:
    image: nginx
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    volumes_from:
      - web
    depends_on:
      - web
    ports:
      - "80:80"
